global:
  smtp_smarthost: 'localhost:25'
  smtp_from: 'yourprometheus@example.com'

route:
  receiver: example-email
  group_by: [alertname]

receivers:
  - name: example-email
    email_configs:
      - to: 'youraddress@example.com'

#route:
#  receiver: 'mail'
#  repeat_interval: 4h
#  group_by: [ alertname ]
#
#
#receivers:
#  - name: 'mail'
#    email_configs:
#      - smarthost: 'smtp.gmail.com:465'
#        auth_username: 'your_mail@gmail.com'
#        auth_password: ""
#        from: 'your_mail@gmail.com'
#        to: 'some_mail@gmail.com'