version: '3'

services:

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
#    depends_on:
#      - prometheus

  blackbox-exporter:
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yaml:/etc/blackbox_exporter/config.yml
#    depends_on:
#      - prometheus

  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
#    command: --config.file=/config/alertmanager.yml --log.level=debug