global:
  scrape_interval: 15s
  evaluation_interval: 10s

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.0.87:8888']


#
#  - job_name: 'postgres'
#    metrics_path: /metrics
#    params:
#      format: [text]
#    static_configs:
#      - targets: ['192.168.0.87:5432']
#
#  - job_name: 'redis'
#    metrics_path: /metrics
#    params:
#      format: [text]
#    static_configs:


  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: ['blackbox-exporter:9115']
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115